[Icon Theme]
Name=Koollook
Comment=Liwi griffin brand icons for Koollook
Inherits=breeze,hicolor
Directories=apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/128,apps/256,apps/scalable,places/16,places/22,places/24,places/32,places/48,places/64,places/128,places/256,places/scalable
FollowsColorScheme=true
DisplayDepth=32
DesktopDefault=48
DesktopSizes=16,22,24,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24
PanelDefault=48
PanelSizes=16,22,24,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,24,32,48,64,128,256
Example=koollook

[apps/16]
Size=16
Type=Fixed
Context=Applications

[apps/22]
Size=22
Type=Fixed
Context=Applications

[apps/24]
Size=24
Type=Fixed
Context=Applications

[apps/32]
Size=32
Type=Fixed
Context=Applications

[apps/48]
Size=48
Type=Fixed
Context=Applications

[apps/64]
Size=64
Type=Fixed
Context=Applications

[apps/128]
Size=128
Type=Fixed
Context=Applications

[apps/256]
Size=256
Type=Fixed
Context=Applications

[apps/scalable]
Size=256
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[places/16]
Size=16
Type=Fixed
Context=Places

[places/22]
Size=22
Type=Fixed
Context=Places

[places/24]
Size=24
Type=Fixed
Context=Places

[places/32]
Size=32
Type=Fixed
Context=Places

[places/48]
Size=48
Type=Fixed
Context=Places

[places/64]
Size=64
Type=Fixed
Context=Places

[places/128]
Size=128
Type=Fixed
Context=Places

[places/256]
Size=256
Type=Fixed
Context=Places

[places/scalable]
Size=256
MinSize=16
MaxSize=512
Type=Scalable
Context=Places
